FROM quay.io/keycloak/keycloak:23.0.7

# Copy any custom themes or providers
COPY keycloak/themes/ /opt/keycloak/themes/
COPY keycloak/custom-providers/ /opt/keycloak/providers/

# Build Keycloak with PostgreSQL support and admin console
RUN /opt/keycloak/bin/kc.sh build \
    --db=postgres \
    --health-enabled=true \
    --metrics-enabled=true \
    --cache=ispn \
    --cache-stack=tcp

# Set default command
CMD ["start", "--optimized"]